# Khai báo nhóm Load Balancer (Đổi tên app1, app2 đúng với service trong docker-compose của bạn)
upstream goldenowl_backend {
    server goldenowl-app-1:80;
    server goldenowl-app-2:80;
}

# 1. HTTP (80) -> Redirect sang HTTPS
server {
    listen 80;
    server_name shuttlex.io.vn;

    return 301 https://$host$request_uri;
}

# 2. HTTPS (443)
server {
    listen 443 ssl;
    server_name shuttlex.io.vn;

    ssl_certificate     /goldenowl-app/nginx/certs/cloudflare.crt;
    ssl_certificate_key /goldenowl-app/nginx/certs/cloudflare.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://goldenowl_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}